name: First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: welcome message
        run: echo "Welcome to the first workflow!"

      - name: list files
        run: ls -la
      - name: print working directory
        run: pwd
      - name: read files
        run: cat README.md
